name: comprehensive_utils
description: A collection of classes and functions containing simple and complex performance-oriented tools
version: 0.6.3
repository: https://github.com/kdomon231/comprehensive_utils

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.11.0
  rxdart: ^0.27.7
  fast_immutable_collections: ^10.2.3
  async_builder: ^1.3.1+1
  nil: ^1.1.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true